### ISSUE TITLE
`lasso_user_can()` returns false in WP 4.2.3 when is an admin user

### ISSUE THREAD

**Issue by Shelob9** [AesopInteractive/lasso#101]

**Comment by bearded-avenger** [comment]
We can't just change this without testing. The reason it was edit_posts is because it was failing with edit_post. I'd like to leave as is until we can fully test it.

**Comment by bearded-avenger** [comment]
edit_post is for single, edit_posts is for blanket across the board. the caps change when we're on a single. edit_post requires a post_id. it just results in php warnings so the logic just needs to be fully vetted (which I thought I already did)

**Comment by michaelbeil** [comment]
I just sent a different PR (#103) to stay with our git flow is all. User is not able to save posts with Lasso 0.9.6 and WP 4.2.3. I am all for greater testing.

**Comment by Shelob9** [comment]
I agree. It's a massive change with like 400 implications, needs situational unit tests.

**Comment by bearded-avenger** [comment]
that is ONE user correct?

**Comment by michaelbeil** [comment]
Yea, and myself too.

**Comment by Shelob9** [comment]
I confirmed issue as well.

**Comment by bearded-avenger** [comment]
that guy has all kinds of cloudflare junk going on. its not a widespread issue. I've never encountered not being able to save a post as admin

**Comment by bearded-avenger** [comment]
I agree @Shelob9 unit tests for this would help

**Comment by michaelbeil** [comment]
It is true that he has all kinds of crapola, however, this has been replicable on both our setups. Does this happen for you on the latest WP @bearded-avengeR?

**Comment by bearded-avenger** [comment]
if users were not able to save a post as admin our support would just be going crazy

**Comment by bearded-avenger** [comment]
unless something changed with caps in 4.2.3

**Comment by bearded-avenger** [comment]
sure as shit, something changed in 4.2.3. awesome. LMAO

**Comment by bearded-avenger** [comment]
so much for a SECURITY release LOLOLOL

**Comment by michaelbeil** [comment]
Yea, unless many have not updated. Still does not answer my question, heh. And yes, there was a friggin change. This was not that great of an iteration for devs as it was supposed to be security related. https://core.trac.wordpress.org/milestone/4.2.3 and https://codex.wordpress.org/Version_4.2.3 ~~> `wp-includes/capabilities.php`.

**Comment by bearded-avenger** [comment]
thanks @michaelbeil

**Comment by bearded-avenger** [comment]
no wonder devs are going ape shit this is crap

**Comment by michaelbeil** [comment]
YAH sure you betcha der hey down in the mountains bearder feller.

**Comment by bearded-avenger** [comment]
LMAO

**Comment by michaelbeil** [comment]
Seriously. The entire shortcode API got lambasted.

**Comment by bearded-avenger** [comment]
yeah that's sep I'm more concerned with what's changed with caps that has pretty far reaching effects that a lot of people won't even notice with their plugins for some time. I'm eager to a diff on wp-capabilities now

**Comment by michaelbeil** [comment]
Yea, it was a wrong way of doing things for sure, re shortcodes. Bummer that it was done and over with in literally 30 hours without informing devs.

You are right on the caps stuff.

**Comment by bearded-avenger** [comment]
just lost a bit more faith in wordpress

**Comment by bearded-avenger** [comment]
i'll look more tomorrow but in my 2 min of diffing it seems like if no post object it now passes do_not_allow https://github.com/WordPress/WordPress/commit/fe5a844be57adecb3f7b74bfcd1d8b8f153eedc4

**Comment by michaelbeil** [comment]
yea, i think that was the response we were getting back from our internal api via json as well

**Comment by bearded-avenger** [comment]
well thanks for being on top of it guys I appreciate it. I've been out of the loop the past couple of weeks

**Comment by michaelbeil** [comment]
fyi, that commit is on `4.3-beta3-33357`.

**Comment by bearded-avenger** [comment]
yeah you're right I was just looking back on the history of changes to that file https://github.com/WordPress/WordPress/commits/fe5a844be57adecb3f7b74bfcd1d8b8f153eedc4/wp-includes/capabilities.php

**Comment by bearded-avenger** [comment]
https://core.trac.wordpress.org/ticket/33154

**Comment by michaelbeil** [comment]
There she blows.

**Comment by bearded-avenger** [comment]
this broke role restrictions. a contributor can now edit other users posts. :( I was afraid that this would happen with this change.

**Comment by bearded-avenger** [comment]
I'm not going to be able to get to this until at least Friday.
