### ISSUE TITLE
Embed.ly preview integration

### ISSUE THREAD

**Issue by nkeat12** [AesopInteractive/lasso#106]
I've been trying to get this integration setup with the jQuery preview plugin by embed.ly but it needs to be able to listen to a form on submit I believe. 

Any guidence on a possible way to integrate this with Lasso w/o editing the core files?

https://github.com/embedly/jquery-preview

Thanks!

**Comment by michaelbeil** [comment]
Hey @nkeat12,

Great question, but unfortunately this repository is not a support forum, and is meant for bug reports and code submissions for future iterations of Editus. If you have bought a license key, you can contact support from your account at http://edituswp.com.
