### ISSUE TITLE
No more lasso_runs_on / editus_runs_on ?

### ISSUE THREAD

**Issue by agenceKanvas** [AesopInteractive/lasso#110]
I've read the documentation but it seems that there is no more lasso_runs_on filter, or editus_runs_on neither.
It's not possible anymore to restrict editus to a particular post type ? Or user group ?

**Comment by hyunsupul** [comment]
I am not the original author. But It seems like the place to control the post types and other kinds of restrictions are lasso_user_can

Now this pluggable function is not perfect because this does not control some menus. But the capability can be controlled by plugging in lasso_user_can.

**Comment by hyunsupul** [comment]
I believe the documentation just needs to be corrected.
