### ISSUE TITLE
Uncaught TypeError: wp.api.collections.Posts is not a constructor

### ISSUE THREAD

**Issue by frankoonk** [AesopInteractive/lasso#118]
Hi,

When i update to wordpress 4.7 (with rest api included), disable the Wp Rest V1 plugin  and update Editus to 0.9.13. I get this error:

lasso.js:13746 Uncaught TypeError: wp.api.collections.Posts is not a constructor(…)

I can't figure out, what's causing it.

**Comment by hyunsupul** [comment]
This should have been fixed with the latest version of Editus
