### ISSUE TITLE
AJAX error on save

### ISSUE THREAD

**Issue by Madcore** [AesopInteractive/lasso#119]
Hi.

Everytime I try to create or edit a post, when I click on the save button, this error appears:

**AJAX Error: The requested page not found. [404]**

I don't know why it happens. I deactivated some plugisn, but it still appears.

**Comment by hyunsupul** [comment]
Now Editus uses REST API V2 to save whenever possible. So far, as long as REST API endpoint is active, Editus should be able to save posts without this AJAX error.
