### ISSUE TITLE
Page Jumps to Top When Copy and Pasting in Mac/Chrome/Firefox

### ISSUE THREAD

**Issue by davidrichied** [AesopInteractive/lasso#121]
When I copy and paste something on the front end (after clicking the little pen to make the content editable), the page either jumps to the bottom when using one theme (my custom theme), or it jumps to the top when using another theme (Twenty Seventeen).

I'm not sure how to even debug this. I tried it on Chrome and Firefox and with the Twenty Seventeen theme.

Any thoughts?

**Comment by hyunsupul** [comment]
This should have been fixed with the very latest version. Thank you,
