### ISSUE TITLE
Revision System

### ISSUE THREAD

**Issue by bearded-avenger** [AesopInteractive/lasso#3]
auto saving draft with option to restore
- [x] user interface
- [x] surface private revisions through rest api

**Comment by michaelbeil** [comment]
Need some type of revision system that automatically saves every 60 seconds and stores the last 5 copies with wp insert revision, with option to restore.

**Comment by bearded-avenger** [comment]
pity you can't have two assignees!

**Comment by michaelbeil** [comment]
here ya go: both @bearded-avenger and @Shelob9 are assigned :).
- [x] @bearded-avenger
- [x] @shelob9

**Comment by bearded-avenger** [comment]
to make things more fun, we could access revisions with the json api since we're already using it. we would just need authenticate the user

**Comment by michaelbeil** [comment]
API all the things. That is a great idea @bearded-avenger.

**Comment by bearded-avenger** [comment]
Some notes on a chat Josh and I had:
- josh to work on surfacing private revisions through rest api
- nick to build up interface

User clicks the revision icon, modal open with the list of revisions for that post. You click an eye/preview button, it replaces the post with the revision with the highlighted text as what's changed. The save button becomes the restore button. You can nav through revisions with arrows, with the revision replacing the post content.

**Comment by Shelob9** [comment]
When in revision  browse, the X cancel button becomes exit revision browse without restoring.

**Comment by bearded-avenger** [comment]
Alright, Josh put a major dent in this so props Josh!

With data on board, it's time to bring it to life. I first tried just rolling with the idea that we came up with of navigating through live revisions with arrows, but the more I kept using it, the more it just didn't feel right. So instead, opted for a slider handle so it's a somewhat familiar control. Using this, the left most point is current, and you go back in time  by sliding it right.

There's a few quirks with the positioning of the marker items, this should ideally be binded to the available slider increments. Also, this is far from complete but it is working.

![image 2015-06-20 at 10 30 46 am](https://cloud.githubusercontent.com/assets/1317303/8267918/aec23cd6-1737-11e5-820b-8191869bd0a2.png)

https://github.com/AesopInteractive/lasso/tree/feature/revisions

The user loads up the revisions, and where normally the page is locked for scrolling, it will allow them to scroll to view the content with the revision modal over top. When a user slides to a revision, it restores it. When a user clicks "select" it closes the modal and opens the editor.

So within 3 clicks, a user can be working on a restored copy of their post.

**Comment by bearded-avenger** [comment]
alright sent up a few more commits this morning which include appending a notice if the user is editing a backup, and also if a user is editing a backup, and loads up the revision modal, the slider is restored to the current revision.

I'm calling this feature complete and ready for testing.

**Comment by bearded-avenger** [comment]
tossed in an empty state for a post that has no revisions

![image 2015-06-21 at 8 56 44 am](https://cloud.githubusercontent.com/assets/1317303/8271877/7c76f5e8-17f3-11e5-8eca-7aac10e789f6.png)
