### ISSUE TITLE
Characters like æ, ø, og, å are converting to gibberish

### ISSUE THREAD

**Issue by michaelbeil** [AesopInteractive/lasso#44]
"@aesopinteractiv When trying to use æ. ø og å in the Lasso editor the letters is converted to gibberish like Ã¸ and Ã¦. :-(" https://twitter.com/fiwa/status/585341603339972608

**Comment by solhuebner** [comment]
:+1:

**Comment by bearded-avenger** [comment]
this must have been cleared up somewhere long the way because I can't get it to turn to jibberish anymore. http://cl.ly/image/0O1c2C3r2J1z
