### ISSUE TITLE
Content does not save when post is created from WordPress backend

### ISSUE THREAD

**Issue by Nikschavan** [AesopInteractive/lasso#57]
When a new page or post is created from backend and then edited in the front-end, any content added to the post is not saved to the post.

[Screencast](https://www.dropbox.com/s/lgr6dwh1uw0bn0k/2015-05-16_20-45-28.mp4?dl=0)

**Comment by bearded-avenger** [comment]
What branch? What version? There's quite a few people using this a daily basis and there are no reports of this. I also use this plugin daily and haven't run across this.

**Comment by michaelbeil** [comment]
I have not seen this behavior either. 

When you get a chance, @nikschavan, would you share the details mentioned by @bearded-avenger above? 

Also, would you create a new post from the front-end and let us know the results?

**Comment by Nikschavan** [comment]
@bearded-avenger I am on master, v0.9.3, I tried checking out to dev branch still the issue exists.
@michaelbeil Creating new post from front end works just fine as expected.

Upon digging into this more, the ajax request that is being sent to 'lasso-internal-api' the "content" is empty.

[screencast](https://www.dropbox.com/s/sepvxtka3vbdqa0/2015-05-16_21-43-54.mp4?dl=0)

I am using this with 2015 Theme, and here are me classes in lasso settings - ![lasso settings](http://i.imgur.com/p7GagH2.png) Is there anything wrong with my settings that might be causing this?

I am setting up Grunt, lets see if there is anything I can do to it.

**Comment by bearded-avenger** [comment]
We can't provide you with support unless you purchase a license key. I can assure you that the basic feature of saving, is working. If not we'd be hearing it from everyone who has purchased. You likely have things setup incorrectly, but again, we can't help you unless you purchase a support license.

**Comment by Nikschavan** [comment]
Turns out this was because of incorrect settings.
I am not looking for support, I am a looking into this plugin from addon developers perspective.
This is one interesting plugin.

**Comment by bearded-avenger** [comment]
Glad to hear. 

This is the first commercially sold plugin that I've made public, and we're still trying to find our footing with where to draw the line with what is considered support, and what is considered helping with a legit bug.

**Comment by michaelbeil** [comment]
Great news @Nikschavan. 

Let us know if you run into any other bugs and do ping us when/if you create an addon.
