### ISSUE TITLE
JS should load unminified if SCRIPT_DEBUG

### ISSUE THREAD

**Issue by Shelob9** [AesopInteractive/lasso#59]

**Comment by etcook** [comment]
Another option might be just including a map

**Comment by bearded-avenger** [comment]
E! I'm somewhat illiterate when it comes to those things. Is that the same type of map file generated with gulp/grunt?

**Comment by etcook** [comment]
Correct - as long as they're available, Chrome can/will rebuild the original file for debugging.

**Comment by bearded-avenger** [comment]
fixed with commits above
