### ISSUE TITLE
Adding new components to Lasso?

### ISSUE THREAD

**Issue by khromov** [AesopInteractive/lasso#71]
I was looking through the documentation on adding new components to Lasso. So far so good. But I couldn't find the hook to add my own component and it appears that the component list is hard-coded? 

Relevant code:  
https://github.com/AesopInteractive/lasso/blob/f5e2b7014fe7f69ba84bbbbd7368737ad0145928/public/includes/editor-modules.php#L175

Some clarification in the readme would be nice. :+1:

**Comment by bearded-avenger** [comment]
Check out the action on L194. :)

**Comment by bearded-avenger** [comment]
Also, check out the sample addon here: https://github.com/AesopInteractive/sample-addon

**Comment by khromov** [comment]
Thanks @bearded-avenger , I was using the sample addon but this piece of code was stopping the code from executing:
https://github.com/AesopInteractive/sample-addon/blob/master/sample-addon.php#L23

Not sure why as it appears to be a Lasso function? (Using version 0.9.4, is it better to stay on master instead?). Bypassing the conditional makes the component show up.

While I have you on the line, is there any way to keep the shortcodes in Lasso dynamic? For example we use a shortcode that displays the latest posts, and it changes often so we can't just render it once, it has to be done at least every day. Any thoughts on that?

**Comment by bearded-avenger** [comment]
The only way that wouldn't execute is if your copy of Lasso is behind. As far as I can tell it's returning properly in 0.9.4.

![image 2015-05-25 at 11 57 53 am](https://cloud.githubusercontent.com/assets/1317303/7800077/6832628a-02d5-11e5-863a-d657e8e07067.png)

I'm not sure what you mean on making the shortcodes dynamic. They are dynamic by nature

**Comment by bearded-avenger** [comment]
my quick test shows this failing for some reason, I'll look into it

**Comment by bearded-avenger** [comment]
ok try running it under `class_exists( 'lasso_autoloader' )`

**Comment by khromov** [comment]
No luck, there is no class called lasso_autoloader from what I can tell and the function returns false.

**Comment by bearded-avenger** [comment]
I have tested this and have verified it to be working, and I've also patched the sample addon.

https://github.com/AesopInteractive/lasso/blob/master/includes/lasso_autoloader.php#L12

![image 2015-05-25 at 12 20 50 pm](https://cloud.githubusercontent.com/assets/1317303/7800272/8515013e-02d8-11e5-85ac-d9ae6ca7e0c8.png)

**Comment by khromov** [comment]
@bearded-avenger  Right, it appears I was running 0.9.1 which does not have that class, you must have released 0.9.4 just a few minutes ago. Should be all good.

Did you have any comment regarding my question for dynamic blocks?

**Comment by bearded-avenger** [comment]
Yes 0.9.4 was tagged a few hours ago here on Github, but will be released to license holders via automatic update later today/tomorrow.

Re: dynamic blocks, can you clarify by expounding on your request? Shortcodes are dynamic by default, in the sense that changes to them can update existing implementations of the shortcode.

**Comment by khromov** [comment]
@bearded-avenger From what I have seen so far, if you enter a shortcode while editing a page in Lasso, it won't give you a preview and it will save the rendered HTML representation of that shortcode into the post_content when you save by clicking the Lasso floppy icon.

What we're looking for is keeping the shortcode intact in the post_content so it can be updated over time (like a latest posts list) while still showing the user a nice preview for it.

Consider the Aesop Quote block where you can enter the quote inline. We'd like that to map to something like: `[quote text="what you entered"]`

Are there any examples of doing that available?

**Comment by bearded-avenger** [comment]
Aesop Story Engine shortcodes are processed back and forth when the post is saved/viewed. As long as it's an Aesop component, it will not save the HTML version of it. If you look in the sample addon you can define your component settings there which will be accessible to both Aesop Story Engine on the backend, and Lasso on the front-end.

**Comment by khromov** [comment]
I'll have a peek, thanks @bearded-avenger !

**Comment by bearded-avenger** [comment]
No problem. I'm going to close this issue. Feel free to ping us with any other queries.

**Comment by bearded-avenger** [comment]
I'm going to add a few more commits to the sample addon. Right now it's just showing how to add a custom component that is NOT shortcode based. The only difference is that you should return a shortcode instead of HTML. I think that's where this is causing confusion. Give me a few moments.

**Comment by khromov** [comment]
Awesome, thanks for taking the time @bearded-avenger . :+1:

**Comment by bearded-avenger** [comment]
no problem. so basically in your callback, you should do this:

``` php
    function my_callback(){
        return do_shortcode( '[aesop_test]' );
    }
```

This will then populate your option settings array as you were likely expecting:
![image 2015-05-25 at 12 38 28 pm](https://cloud.githubusercontent.com/assets/1317303/7800440/073611a6-02db-11e5-8f77-dd56c1fc1886.png)

Obviously use your own shortcode name or whatever like `aesop_mynewshortcode`

**Comment by bearded-avenger** [comment]
OK I've just patched up the other sample addon and fixed another bug with the options not mapping back correctly after saving. This should be squared away now and you shouldn't have any other issues.

BTW we introduced a new settings API (beta) that allows you to add settings tab on the settings modal shown on a single post like below. Would love your thoughts if you happen to give this a go. 

![image 2015-05-25 at 12 28 34 pm](https://cloud.githubusercontent.com/assets/1317303/7800588/4465ad50-02dd-11e5-9afe-6258891e0293.png)

**Comment by khromov** [comment]
Great @bearded-avenger , we'll be sure to give it a try.

Putting fields on the post is great. I am especially looking forward to #68 (ACF integration), so that we don't have to run multiple field suites. :+1:

I couldn't find any work-in-progress branches of the ACF feature on GitHub but we'd be interested in giving it a whirl.

**Comment by bearded-avenger** [comment]
awesome! yep that is actually the integration there, #68 . Those 20 lines of code is all it takes. :)

Just smack that into a php file and it'll be a plugin, which you can activate. It's kinda alpha'ish but maybe someone with a deeper understanding of ACF could get around it, or has better ideas.
