### ISSUE TITLE
Search for post

### ISSUE THREAD

**Issue by bearded-avenger** [AesopInteractive/lasso#72]
add ability to search for a post in the all posts modal

**Comment by Shelob9** [comment]
@bearded-avenger Question would this be built with the S query var in WP_Query (should be able to create a client-js view based on s query var very easily BTW) or would it be a custom search system?

**Comment by bearded-avenger** [comment]
my first thought was a return with the JSON API since it's there wp-json/p/XX. Simple query could definitely work for that if not done with the API.

**Comment by Shelob9** [comment]
Seems like if we're going JSON API, this could get built into the existing
all post modal pretty easily. Just modify the current view on key up a
search form.

## 

JoshPress.net http://joshpress.net/
CalderaWP.com http://calderawp.com/
@Josh412 http://twitter.com/Josh412

**Comment by bearded-avenger** [comment]
ref
https://github.com/AesopInteractive/lasso/commit/5c73ac37dd8d2d19ca89c502f70316a7fe74d738
https://github.com/AesopInteractive/lasso/commit/413d616e343b4daef8001c65c25896c3eea54baf
https://github.com/AesopInteractive/lasso/commit/3bedc74f5934e4b837fe3344546110d86c8af3ef
https://github.com/AesopInteractive/lasso/commit/316857e2ada43087500fe5a8d78bc369dc5be951
https://github.com/AesopInteractive/lasso/commit/22afc7247807bcc15ddcaf346d506c371bb4bef3

**Comment by bearded-avenger** [comment]
kinda torn on `keyup` vs `change`

**Comment by michaelbeil** [comment]
both? 

```
$("#element").on('keyup change', function (){
   // Your stuff...
});
```

**Comment by bearded-avenger** [comment]
>  I like suggestions, but don't start searching until I ask you to. Good UX is like a butler...polite, helpful and invisible...

https://twitter.com/ci_chrisford/status/604326603858968576

**Comment by bearded-avenger** [comment]
> after I press enter. Results as I type are distracting, and subconsciously a bit presumptuous.
> https://twitter.com/christinebpc/status/604327064456417280

**Comment by michaelbeil** [comment]
Yes, very true.

**Comment by bearded-avenger** [comment]
kinda buggy, and this gif is janky the colors are all off
![screen recording 2015-05-29 at 11 45 am](https://cloud.githubusercontent.com/assets/1317303/7887675/7184ae30-05f8-11e5-953d-572cfa3147d6.gif)

**Comment by bearded-avenger** [comment]
I think I personally prefer `change` instead of `keyup`

**Comment by michaelbeil** [comment]
yea, weird coloration going on. anyways, what do you like better about `change`?

**Comment by bearded-avenger** [comment]
I think it's more predictable, and my thoughts are along the lines of Christine.

**Comment by michaelbeil** [comment]
I think that's the better route then. Her thought seemed most pertinent.

**Comment by bearded-avenger** [comment]
In this context, it's not a user searching for some article on how to widdle wood on the logged out view of a website, so I think the predictive nature in that context is great. But here the user likely knows what part of the post is titled, so I wonder if predictive wouldn't be great in this context.

**Comment by michaelbeil** [comment]
I mean predictive can make the process faster. Contextually, the user will most likely be going about their site with speed and efficiency in mind.

**Comment by bearded-avenger** [comment]
alright here's latest, gotta shift focus to actual work now ;)

http://cl.ly/0G1t0N0j340z

**Comment by bearded-avenger** [comment]
The only thing stopping this from being fully complete is pagination, which I can't find the endpoint for in the REST API (V1). `wp-json/posts?filter[s]=test?page=2` should be working but it's returning empty.

None of these work either:
`wp-json/posts?filter[s]=test?[page]=2`
`wp-json/posts?filter[s]=test?[paged]=2`

**Comment by bearded-avenger** [comment]
pushed out a first version that returns 50 results, lazy load to come
