### ISSUE TITLE
Metabox Option API

### ISSUE THREAD

**Issue by bearded-avenger** [AesopInteractive/lasso#79]
ability for themes to hook into the Lasso Option API and include their own post meta options that Lasso will turn into forms, taking care of security and sanitization.

**Comment by michaelbeil** [comment]
This is going to be stellar.

**Comment by bearded-avenger** [comment]
@Shelob9  how can I pass unknown __POST objects through the params() of the internal api? for example, a user creates their own meta fields, we dont know the name of the field, so it’s not coming across in $data 

https://github.com/AesopInteractive/lasso/blob/feature/option-api/includes/process/meta.php#L49

**Comment by bearded-avenger** [comment]
hrm, i may just skirt around this by predictably naming the key name according to the option type.

**Comment by bearded-avenger** [comment]
Alright so that logic above wont work. If we can't send a entire post object through the internal api might just let this hit admin-ajax

**Comment by bearded-avenger** [comment]
merged to 0.9.5

**Comment by bearded-avenger** [comment]
https://gist.github.com/bearded-avenger/a4be4ea9572590f2a8ad

**Comment by bearded-avenger** [comment]
Alright this is fully working and the last few bugs being sent out with 0.9.6. A sample addon https://github.com/AesopInteractive/lasso-yoast
