### ISSUE TITLE
Document insertion putting spurious jQuery code in the_content

### ISSUE THREAD

**Issue by zamoose** [AesopInteractive/lasso#87]
When I add e.g. a PDF, save, and then reload the page, the following is inserted into the content, in the raw:

``` javascript
            jQuery(document).ready(function($){
                $('.aesop-doc-reveal-2-1').click(function(e){
                    e.preventDefault;
                    $( "#aesop-doc-collapse-2-1" ).slideToggle();
                    return false;
                });
            });
```

**Comment by bearded-avenger** [comment]
what up mr doug! Yep noticed this a couple days ago, and pushed a fix into Aesop 1.6.3 branch, should be out in the next week or so. https://github.com/bearded-avenger/aesop-core/commit/e4f7b68b339519fb8e436c1688591874b8371806

**Comment by michaelbeil** [comment]
We already have something in the que for ASE 1.6.3 that works out this doc issue.

**Comment by michaelbeil** [comment]
@bearded-avenger wins the Internet with fastest reply.

**Comment by bearded-avenger** [comment]
![giphy](https://cloud.githubusercontent.com/assets/1317303/8091957/8343fb52-0f7c-11e5-89fa-c1f1e6bd0efb.gif)

**Comment by michaelbeil** [comment]
![giphy-1](https://cloud.githubusercontent.com/assets/4752949/8092252/25207396-0f7e-11e5-81ca-67576f0bcbfb.gif)
![giphy](https://cloud.githubusercontent.com/assets/4752949/8092254/270628fe-0f7e-11e5-9099-c06a47042570.gif)

**Comment by zamoose** [comment]
Nice! I'll wait for it patiently.

![yaymchale](https://cloud.githubusercontent.com/assets/862531/8092295/c963790a-0f86-11e5-8462-23212785aa76.gif)

**Comment by bearded-avenger** [comment]
OK Aesop Story Engine 1.6.3 just went out with this fix.

**Comment by michaelbeil** [comment]
Yay!
![image](http://media0.giphy.com/media/QajZ8itPzs4jC/giphy.gif)
