### ISSUE TITLE
Duplicate post/page on new post/page creation

### ISSUE THREAD

**Issue by michaelbeil** [AesopInteractive/lasso#92]
Master has a bug, that goes back to our latest release of 0.9.5, where there is a duplication happening.

![slack-imgs-1 com](https://cloud.githubusercontent.com/assets/4752949/8239920/9c55764a-15c4-11e5-80f7-9e7bf9115603.png)

**Comment by bearded-avenger** [comment]
The form isn't submitting twice and neither is the AJAX call I tested both of these. As far as I can tell the internal API is running twice for this?

**Comment by bearded-avenger** [comment]
I tracked this down to the API itself. When kill the process what creates a post, the API returns an error twice. I think the updates to the meta option api are what's causing this. This means that the api is running twice for EVERy action created. :(

**Comment by Shelob9** [comment]
That doesn't use lasso-internal-api that uses the wp api via the client.js

**Comment by bearded-avenger** [comment]
![image 2015-06-18 at 2 48 34 pm](https://cloud.githubusercontent.com/assets/1317303/8243256/15fdf29a-15db-11e5-956c-db74ad34809d.png)

**Comment by bearded-avenger** [comment]
when i wp_die() at the point where it runs wp_insert_post, it returns two errors instead of one. any thoughts?

**Comment by Shelob9** [comment]
I think I need to make time to reproduce this locally.
